MOUSEKEY_ENABLE = no
VIA_ENABLE = yes
LTO_ENABLE = yes
OPENRGB_ENABLE = yes

#OPT_DEFS += -DVIA_OPENRGB_HYBRID_APPEND_COMMAND
#OPT_DEFS += -DVIA_OPENRGB_HYBRID_CUSTOM_KEYCODE

#DEBOUNCE_TYPE = sym_eager_pk
